# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e07d79427d6c75e4a8abe524c4b2aff7ea10934ecc3a9b959a18014ecee0f4806afd6a8d668b368f55f09517db06a3e905c1bfb9f679e47a5531c69161345579

test:
  secret_key_base: 5aa1ba2ad860803541ae2cf6229073c5d99fb3ebccf824b633cca7d8144c201784870476b7b6a1bae1f7f0afb00be2430f177c3f3bb1ab25455ac5336df60e5d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
